import * as fs from 'fs';
import * as path from 'path';

// Dictionary of question ID -> accurate, complete, step-by-step mathematical explanation
export const EXPLANATION_CORRECTIONS: Record<string, string> = {
  // === CLASS 9 MATHEMATICS ===
  'c9-ch2-q15': 'By the definition of logarithms, $b^y = x \\iff \\log_b(x) = y$. Since $10^3 = 1000$, taking the logarithm to base $10$ yields $\\log_{10}(1000) = 3$.',
  'c9-ch2-q33': 'Converting the logarithmic equation $\\log_2 x = 4$ into its equivalent exponential form gives $x = 2^4 = 16$.',
  'c9-ch2-q34': 'Converting the logarithmic equation $\\log_5 x = 3$ into its equivalent exponential form gives $x = 5^3 = 125$.',
  'c9-ch2-q35': 'Converting the logarithmic equation $\\log_3 x = 2$ into its equivalent exponential form gives $x = 3^2 = 9$.',
  'c9-ch3-q11': 'Factoring out the common variable $a$ using the distributive law gives $9a - 4a = (9 - 4)a = 5a$.',
  'c9-ch3-q14': 'Substituting $x = 4$ into the algebraic expression $2x + 3$ yields $2(4) + 3 = 8 + 3 = 11$.',
  'c9-ch3-q16': 'Substituting the given values $a = 2$ and $b = 3$ into the sum $a + b$ yields $2 + 3 = 5$.',
  'c9-ch3-q17': 'Substituting the given values $a = 2$ and $b = 3$ into the product $ab$ yields $2 \\times 3 = 6$.',
  'c9-ch3-q18': 'By the distributive property of multiplication over addition, multiplying $a$ by each term inside the parentheses $(b + c)$ gives $a(b + c) = ab + ac$.',
  'c9-ch3-q44': 'Distribute the factor $3$ and then combine like terms: $3(x + 2) - x = 3x + 6 - x = (3x - x) + 6 = 2x + 6$.',
  'c9-ch3-q47': 'Substitute $a = 3$ and $b = 2$ into the difference of squares: $a^2 - b^2 = 3^2 - 2^2 = 9 - 4 = 5$.',
  'c9-ch3-q49': 'Factoring out the like variable $x$: $4x + 6x - 3x = (4 + 6 - 3)x = 7x$.',
  'c9-ch5-q24': 'Multiply numerators and denominators: $\\frac{x}{2} \\times \\frac{4}{x} = \\frac{4x}{2x} = \\frac{4}{2} = 2$, provided $x \\ne 0$.',
  'c9-ch5-q25': 'Using the quotient rule of exponents $\\frac{a^m}{a^n} = a^{m-n}$, we have $\\frac{x^2}{x} = x^{2-1} = x$ for $x \\ne 0$.',
  'c9-ch6-q3': 'Subtracting $5$ from both sides of the linear equation $x + 5 = 12$ gives $x = 12 - 5 = 7$.',
  'c9-ch6-q4': 'Adding $7$ to both sides of the linear equation $x - 7 = 3$ gives $x = 3 + 7 = 10$.',
  'c9-ch6-q5': 'Dividing both sides of the linear equation $3x = 15$ by $3$ gives $x = \\frac{15}{3} = 5$.',
  'c9-ch6-q6': 'Multiplying both sides of the equation $\\frac{x}{4} = 3$ by $4$ gives $x = 3 \\times 4 = 12$.',
  'c9-ch6-q24': 'Adding $1$ to both sides yields $3x = 8 + 1 = 9$. Dividing by $3$ gives $x = \\frac{9}{3} = 3$.',
  'c9-ch6-q43': 'Multiplying both sides of the equation $\\frac{x}{5} = 4$ by $5$ yields $x = 4 \\times 5 = 20$.',
  'c9-ch7-q35': 'Substitute $x = 0$ into the linear relation: $y = 2(0) + 1 = 0 + 1 = 1$.',
  'c9-ch7-q36': 'Substitute $x = 2$ into the linear relation: $y = 2(2) + 1 = 4 + 1 = 5$.',
  'c9-ch8-q5': 'Comparing $3x^2 + 5x + 2 = 0$ with the general quadratic form $ax^2 + bx + c = 0$, we identify coefficient $a = 3$, $b = 5$, and constant term $c = 2$.',
  'c9-ch8-q14': 'For a general quadratic equation $ax^2 + bx + c = 0$, the discriminant that determines the nature of the roots is given by the formula $D = b^2 - 4ac$.',
  'c9-ch8-q40': 'To complete the square in $x^2 + 6x$, take half the coefficient of $x$ and square it: $\\left(\\frac{6}{2}\\right)^2 = 3^2 = 9$.',
  'c9-ch8-q41': 'To complete the square in $x^2 + 8x$, take half the coefficient of $x$ and square it: $\\left(\\frac{8}{2}\\right)^2 = 4^2 = 16$.',
  'c9-ch11-q26': 'By definition, the right bisector divides the line segment into two equal halves perpendicular to it: $\\frac{8\\text{ cm}}{2} = 4\\text{ cm}$ each.',
  'c9-ch14-q3': 'In a ratio $a : b$, the first term $a$ is called the antecedent and the second term $b$ is called the consequent.',
  'c9-ch14-q33': 'For similar triangles, the ratio of their areas equals the square of the ratio of corresponding sides: $\\frac{\\text{Area}_1}{\\text{Area}_2} = \\left(\\frac{s_1}{s_2}\\right)^2 = \\frac{16}{25} \\implies \\frac{s_1}{s_2} = \\sqrt{\\frac{16}{25}} = \\frac{4}{5} = 4 : 5$.',
  'c9-ch16-q31': 'Two non-vertical perpendicular lines satisfy the condition $m_1 m_2 = -1$. Given $m_1 = 3$, the perpendicular slope is $m_2 = -\\frac{1}{m_1} = -\\frac{1}{3}$.',
  'c9-ch16-q33': 'Comparing the given equation $y = 3x - 5$ with the slope-intercept form $y = mx + c$, the slope is $m = 3$.',

  // === CLASS 10 MATHEMATICS ===
  'c10-ch2-q6': 'Substituting $x = 4$ into the direct variation relation $y = 3x$ gives $y = 3(4) = 12$.',
  'c10-ch2-q7': 'Substituting $x = 5$ into the inverse variation relation $y = \\frac{20}{x}$ gives $y = \\frac{20}{5} = 4$.',
  'c10-ch2-q11': 'Given $xy = 24$ with $x = 6$, solving for $y$ yields $y = \\frac{24}{6} = 4$.',
  'c10-ch2-q22': 'Substituting $x = 7$ into the direct variation equation $y = 2x$ yields $y = 2 \\times 7 = 14$.',
  'c10-ch2-q23': 'Substituting $x = 10$ into the inverse variation equation $y = \\frac{30}{x}$ yields $y = \\frac{30}{10} = 3$.',
  'c10-ch2-q25': 'Given $xy = 36$ with $y = 9$, solving for $x$ yields $x = \\frac{36}{9} = 4$.',
  'c10-ch2-q32': 'Substituting $x = 0$ into the direct variation relation $y = 7x$ yields $y = 7(0) = 0$.',
  'c10-ch2-q34': 'Given $xy = 40$ with $x = 8$, solving for $y$ yields $y = \\frac{40}{8} = 5$.',
  'c10-ch2-q45': 'Substituting $x = 5$ into the direct variation equation $y = 6x$ gives $y = 6 \\times 5 = 30$.',
  'c10-ch2-q46': 'Given $xy = 60$ with $x = 12$, solving for $y$ gives $y = \\frac{60}{12} = 5$.',
  'c10-ch2-q47': 'Substituting $x = 8$ into the inverse variation equation $y = \\frac{40}{x}$ gives $y = \\frac{40}{8} = 5$.',
  'c10-ch5-q11': 'Substitute $(x, y) = (2, 3)$ into the equation: $2(2) + 3 = 4 + 3 = 7$, satisfying $2x + y = 7$.',
  'c10-ch5-q14': 'By definition in coordinate geometry, the $x$-intercept is the point where the line crosses the $x$-axis, which corresponds to the horizontal line $y = 0$.',
  'c10-ch5-q42': 'The slope of a straight line is defined as $m = \\tan\\theta$. When the inclination angle is $\\theta = 0^\\circ$, $m = \\tan(0^\\circ) = 0$.',
  'c10-ch6-q10': 'The range of a dataset is defined as the difference between the maximum and minimum observations: $\\text{Range} = X_{\\max} - X_{\\min} = 30 - 5 = 25$.',
  'c10-ch6-q23': 'The class width $h$ is calculated as the difference between the upper and lower limits of the class interval: $h = 30 - 20 = 10$.',
  'c10-ch6-q33': 'For the ordered dataset $(2, 4, 6, 8)$ with $n = 4$ observations, the median is the arithmetic mean of the two middle terms: $\\text{Median} = \\frac{4 + 6}{2} = 5$.',
  'c10-ch7-q20': 'On the unit circle where coordinates are $(\\cos\\theta, \\sin\\theta)$, at an angle of $0^\\circ$ the terminal side lies on the positive $x$-axis at $(1, 0)$, so the $y$-coordinate gives $\\sin(0^\\circ) = 0$.',
  'c10-ch7-q24': 'On the unit circle, the point corresponding to an angle of $90^\\circ$ is $(0, 1)$, so the $y$-coordinate gives $\\sin 90^\\circ = 1$.',
  'c10-ch7-q25': 'On the unit circle, the point corresponding to an angle of $0^\\circ$ is $(1, 0)$, so the $x$-coordinate gives $\\cos 0^\\circ = 1$.',
  'c10-ch7-q28': 'On the unit circle, the point corresponding to an angle of $90^\\circ$ is $(0, 1)$, so the $x$-coordinate gives $\\cos 90^\\circ = 0$.',
  'c10-ch14-q47': 'Comparing the equation $x^2 + y^2 = 9$ with the standard form of a circle centered at origin $x^2 + y^2 = r^2$, we have $r^2 = 9 \\implies r = \\sqrt{9} = 3$.',

  // === CLASS 11 MATHEMATICS ===
  'c11-ch1-normal-q15': 'For a complex number $z = a + bi$, the complex conjugate is $\\bar{z} = a - bi$. If $z = \\bar{z}$, then $a + bi = a - bi \\implies 2bi = 0 \\implies b = 0$. Since the imaginary part is zero, $z = a$, which is purely Real.',
  'c11-ch1-normal-q63': 'The modulus is $|x + 4i| = \\sqrt{x^2 + 4^2} = \\sqrt{x^2 + 16} = 5$. Squaring both sides yields $x^2 + 16 = 25 \\implies x^2 = 9 \\implies x = \\pm 3$.',
  'c11-ch1-normal-q109': 'Given $z + \\frac{1}{z} = 0$, multiplying by $z$ gives $z^2 + 1 = 0 \\implies z^2 = -1 \\implies z = \\pm\\sqrt{-1} = \\pm i$.',
  'c11-ch1-normal-q123': 'Combining the terms: $(x + iy) + (x - iy) = 2x = 10 \\implies x = \\frac{10}{2} = 5$.',
  'c11-ch1-normal-q125': 'The modulus is $|4 + yi| = \\sqrt{4^2 + y^2} = \\sqrt{16 + y^2} = 5$. Squaring both sides yields $16 + y^2 = 25 \\implies y^2 = 9 \\implies y = \\pm 3$.',
  'c11-ch1-normal-q180': 'Given $z - \\frac{1}{z} = 0$, multiplying both sides by $z$ gives $z^2 - 1 = 0 \\implies z^2 = 1 \\implies z = \\pm 1$.',
  'c11-ch1-adv-q94': 'Expanding the product: $(x + iy)(1 + i) = (x - y) + (x + y)i = 1 + 5i$. Equating real and imaginary parts gives $x - y = 1$ and $x + y = 5$. Adding these two equations yields $2x = 6 \\implies x = 3$, and substituting into $x + y = 5$ gives $y = 5 - 3 = 2$. Thus $x = 3, y = 2$.',
  'c11-ch1-adv-q182': 'By the triangle inequality, $|z + 1| \\le |z| + |1| = 1 + 1 = 2$. This maximum value of $2$ is attained when $z = 1$.',
  'c11-ch1-adv-q183': 'By the reverse triangle inequality, $|z + 1| \\ge ||z| - 1| = |1 - 1| = 0$. This minimum value of $0$ is attained when $z = -1$.',
  'c11-ch2-normal-q111': 'Evaluating the determinant of the $2 \\times 2$ matrix: $\\det(A) = (1)(4) - (2)(2) = 4 - 4 = 0$. A square matrix with determinant equal to zero is Singular.',
  'c11-ch3-adv-q87': 'Two vectors are perpendicular if and only if their scalar (dot) product is zero: $(1, 2) \\cdot (2, -1) = 1(2) + 2(-1) = 2 - 2 = 0$. Hence, the vectors are perpendicular (Yes).',
  'c11-ch3-adv-q88': 'Two vectors are perpendicular when their dot product vanishes: $(2, k) \\cdot (3, -4) = 2(3) + k(-4) = 6 - 4k = 0 \\implies 4k = 6 \\implies k = \\frac{6}{4} = \\frac{3}{2}$.',
  'c11-ch3-adv-q92': 'Computing the scalar product: $(1, 1) \\cdot (1, -1) = 1(1) + 1(-1) = 1 - 1 = 0$. A zero dot product between non-zero vectors implies they are orthogonal, so the angle between them is $90^\\circ$.',
  'c11-ch3-adv-q193': 'The magnitude of vector $\\mathbf{a} = (x, 2, 2)$ is $|\\mathbf{a}| = \\sqrt{x^2 + 2^2 + 2^2} = \\sqrt{x^2 + 8} = 3$. Squaring both sides yields $x^2 + 8 = 9 \\implies x^2 = 1 \\implies x = \\pm 1$.',
  'c11-ch3-adv-q195': 'Two vectors are parallel if their components are proportional: $\\frac{2}{1} = \\frac{4}{2} = \\frac{6}{k} = 2$. Therefore, $\\frac{6}{k} = 2 \\implies 2k = 6 \\implies k = 3$.',
  'c11-ch4-normal-q38': 'Inserting $3$ arithmetic means between $a = 2$ and $b = 18$ forms an arithmetic progression of $n = 5$ terms. The common difference is $d = \\frac{b - a}{k + 1} = \\frac{18 - 2}{4} = 4$. Thus the three arithmetic means are $2 + 4 = 6$, $6 + 4 = 10$, and $10 + 4 = 14$.',
  'c11-ch4-normal-q51': 'The series is $3(1 + 2 + 3 + \\dots + n) = 3 \\cdot \\frac{n(n+1)}{2} = 165$. Dividing by $3$ gives $\\frac{n(n+1)}{2} = 55 \\implies n(n+1) = 110 \\implies n^2 + n - 110 = 0 \\implies (n - 10)(n + 11) = 0$. Since $n$ must be a positive integer, $n = 10$.',
  'c11-ch4-normal-q58': 'The formula for the $n$-th triangular number is $T_n = \\frac{n(n+1)}{2} = 210$. Multiplying by $2$ gives $n(n+1) = 420 \\implies n^2 + n - 420 = 0 \\implies (n - 20)(n + 21) = 0$. Since $n > 0$, $n = 20$.',
  'c11-ch4-normal-q78': 'Inserting $3$ geometric means between $a = 2$ and $b = 162$ gives a GP of $5$ terms where $a_5 = ar^4 = 162 \\implies 2r^4 = 162 \\implies r^4 = 81 \\implies r = 3$. Hence the three geometric means are $2(3) = 6$, $6(3) = 18$, and $18(3) = 54$.',
  'c11-ch4-normal-q79': 'Inserting $2$ geometric means between $a = 4$ and $b = 108$ gives a GP of $4$ terms where $a_4 = ar^3 = 108 \\implies 4r^3 = 108 \\implies r^3 = 27 \\implies r = 3$. Hence the two geometric means are $4(3) = 12$ and $12(3) = 36$.',
  'c11-ch4-normal-q95': 'The sum to infinity of a convergent geometric series is $S_\\infty = \\frac{a}{1 - r}$. Setting $20 = \\frac{12}{1 - r} \\implies 1 - r = \\frac{12}{20} = \\frac{3}{5} \\implies r = 1 - \\frac{3}{5} = \\frac{2}{5}$.',
  'c11-ch4-normal-q147': 'Summing the four terms of the arithmetic progression: $(x - 3d) + (x - d) + (x + d) + (x + 3d) = 4x = 40 \\implies x = \\frac{40}{4} = 10$.',
  'c11-ch4-normal-q164': 'The sum to infinity is $S_\\infty = \\frac{a}{1 - r} = \\frac{3a}{2}$. Dividing both sides by $a$ gives $\\frac{1}{1 - r} = \\frac{3}{2} \\implies 1 - r = \\frac{2}{3} \\implies r = 1 - \\frac{2}{3} = \\frac{1}{3}$.',
  'c11-ch4-normal-q165': 'Given $S_\\infty = \\frac{a}{1 - r} = 2a$. Dividing both sides by $a$ gives $\\frac{1}{1 - r} = 2 \\implies 1 - r = \\frac{1}{2} \\implies r = 1 - \\frac{1}{2} = \\frac{1}{2}$.',
  'c11-ch4-normal-q172': 'Inserting $2$ geometric means between $a = 2$ and $b = 54$ gives a GP with $a_4 = 2r^3 = 54 \\implies r^3 = 27 \\implies r = 3$. Thus the two geometric means are $2(3) = 6$ and $6(3) = 18$.',
  'c11-ch4-adv-q30': 'In the arithmetic progression $4, 9, 14, 19, \\dots$, the first term is $a = 4$ and common difference is $d = 5$. Using $a_n = a + (n-1)d = 69 \\implies 4 + 5(n-1) = 69 \\implies 5(n-1) = 65 \\implies n - 1 = 13 \\implies n = 14$. Thus $69$ is the 14th term.',
  'c11-ch4-adv-q31': 'In the arithmetic progression $3, 7, 11, \\dots$, $a = 3$ and $d = 4$. Using $a_n = 3 + 4(n-1) = 59 \\implies 4(n-1) = 56 \\implies n - 1 = 14 \\implies n = 15$. Thus $59$ is the 15th term.',
  'c11-ch4-adv-q32': 'In the progression $20, 17, 14, \\dots$, $a = 20$ and $d = -3$. Setting $a_n = 20 - 3(n-1) = -25 \\implies -3(n-1) = -45 \\implies n - 1 = 15 \\implies n = 16$. Thus $-25$ is the 16th term.',
  'c11-ch4-adv-q39': 'For an AP, $a_4 = a + 3d = 14$ and $a_9 = a + 8d = 34$. Subtracting the first equation from the second eliminates $a$: $(a + 8d) - (a + 3d) = 34 - 14 \\implies 5d = 20 \\implies d = \\frac{20}{5} = 4$.',
  'c11-ch4-adv-q98': 'Let the three consecutive AP terms be $a - d, a, a + d$. Their sum is $(a - d) + a + (a + d) = 3a = 30 \\implies a = 10$. Their product is $(10 - d)(10)(10 + d) = 10(100 - d^2) = 960 \\implies 100 - d^2 = 96 \\implies d^2 = 4 \\implies d = 2$. Thus the terms are $10 - 2 = 8$, $10$, and $10 + 2 = 12$.',
  'c11-ch4-adv-q99': 'Let the three AP terms be $a - d, a, a + d$. Their sum is $3a = 21 \\implies a = 7$. The product of the first and third terms is $(7 - d)(7 + d) = 49 - d^2 = 45 \\implies d^2 = 49 - 45 = 4 \\implies d = 2$. Therefore, the terms are $7 - 2 = 5$, $7$, and $7 + 2 = 9$.',
  'c11-ch4-adv-q113': 'In the geometric sequence $2, 6, 18, \\dots$, first term $a = 2$ and common ratio $r = 3$. Setting $a_n = a r^{n-1} = 2(3^{n-1}) = 486 \\implies 3^{n-1} = 243 = 3^5 \\implies n - 1 = 5 \\implies n = 6$. Hence $486$ is the 6th term.',
  'c11-ch4-adv-q114': 'In the geometric progression $1, 2, 4, 8, \\dots$, $a = 1$ and $r = 2$. The $n$-th term is $a_n = 2^{n-1} = 256 = 2^8 \\implies n - 1 = 8 \\implies n = 9$. Thus $256$ is the 9th term.',
  'c11-ch4-adv-q159': 'The sum to infinity is $S_\\infty = \\frac{a}{1 - r}$. Setting $12 = \\frac{6}{1 - r} \\implies 1 - r = \\frac{6}{12} = \\frac{1}{2} \\implies r = 1 - \\frac{1}{2} = \\frac{1}{2}$.',
  'c11-ch4-adv-q161': 'The sum to infinity is $S_\\infty = \\frac{a}{1 - r}$. Setting $6 = \\frac{4}{1 - r} \\implies 1 - r = \\frac{4}{6} = \\frac{2}{3} \\implies r = 1 - \\frac{2}{3} = \\frac{1}{3}$.',
  'c11-ch4-adv-q162': 'The sum of all terms after the first term is $S_\\infty - a = \\frac{a}{1 - r} - a = \\frac{ar}{1 - r}$. Equating this to the first term $a$ gives $\\frac{ar}{1 - r} = a \\implies \\frac{r}{1 - r} = 1 \\implies r = 1 - r \\implies 2r = 1 \\implies r = \\frac{1}{2}$.',
  'c11-ch4-adv-q164': 'For the series $1 + \\frac{1}{3} + \\frac{1}{9} + \\dots$, $a = 1$ and $r = \\frac{1}{3}$. The total sum to infinity is $S_\\infty = \\frac{1}{1 - 1/3} = \\frac{3}{2}$. The sum of all terms after the first term is $S_\\infty - a = \\frac{3}{2} - 1 = \\frac{1}{2}$.',
  'c11-ch5-normal-q116': 'Using the standard series differentiation identity $\\sum_{n=1}^\\infty n x^{n-1} = \\frac{1}{(1-x)^2}$, the given equation is $\\frac{1}{(1-x)^2} = \\frac{9}{4} \\implies 1 - x = \\sqrt{\\frac{4}{9}} = \\frac{2}{3} \\implies x = 1 - \\frac{2}{3} = \\frac{1}{3}$.',
  'c11-ch6-norm-q93': 'Using the combination symmetry identity $\\binom{n}{r} = \\binom{n}{n-r}$, the equation $\\binom{12}{r} = \\binom{12}{3}$ has two solutions: $r = 3$ and the complementary index $r = 12 - 3 = 9$.',
  'c11-ch6-norm-q142': 'The complement of obtaining at least one $6$ in two rolls is obtaining no $6$ on either roll. The probability of no $6$ on one roll is $\\frac{5}{6}$, so for two independent rolls it is $\\left(\\frac{5}{6}\\right)^2 = \\frac{25}{36}$. Therefore, $P(\\text{at least one } 6) = 1 - \\frac{25}{36} = \\frac{11}{36}$.',
  'c11-ch6-norm-q184': 'Each standard six-sided die has $6$ possible independent outcomes. By the fundamental counting principle, two distinguishable dice have $6 \\times 6 = 6^2 = 36$ total outcomes in their sample space.',
  'c11-ch6-norm-q185': 'By the fundamental multiplication principle of combinatorics, for three successive experiments each having $2$ outcomes, the total number of combined outcomes is $2 \\times 2 \\times 2 = 2^3 = 8$.',
  'c11-ch6-adv-q115': 'A standard die has sample space $\\{1, 2, 3, 4, 5, 6\\}$ ($n(S) = 6$). The favorable even outcomes are $\\{2, 4, 6\\}$ ($n(E) = 3$). Thus the probability is $P(E) = \\frac{3}{6} = \\frac{1}{2}$.',
  'c11-ch6-adv-q116': 'The sample space of a fair die is $\\{1, 2, 3, 4, 5, 6\\}$ ($n(S) = 6$). The prime outcomes are $\\{2, 3, 5\\}$ ($n(E) = 3$). Thus the probability of rolling a prime number is $P(E) = \\frac{3}{6} = \\frac{1}{2}$.',
  'c11-ch6-adv-q117': 'The faces on a standard die greater than $4$ are $\\{5, 6\\}$, giving $2$ favorable outcomes out of $6$. Thus the probability is $\\frac{2}{6} = \\frac{1}{3}$.',
  'c11-ch6-adv-q124': 'When two dice are rolled, there are $36$ equally likely outcomes. The pairs with sum equal to $7$ are $(1, 6), (2, 5), (3, 4), (4, 3), (5, 2), (6, 1)$, giving $6$ favorable outcomes. Thus $P(\\text{sum} = 7) = \\frac{6}{36} = \\frac{1}{6}$.',
  'c11-ch6-adv-q130': 'A standard 52-card deck contains $12$ face cards (Jack, Queen, King in each of the 4 suits). The probability of selecting a face card is $\\frac{12}{52} = \\frac{3}{13}$.',
  'c11-ch6-adv-q163': 'Two dice have $36$ outcomes. Sums greater than $9$ are: sum $10$ (3 pairs), sum $11$ (2 pairs), and sum $12$ (1 pair). The total favorable outcomes are $3 + 2 + 1 = 6$. Hence the probability is $\\frac{6}{36} = \\frac{1}{6}$.',
  'c11-ch6-adv-q164': 'Two dice have $36$ outcomes. Sums at most $4$ are: sum $2$ (1 pair: $(1,1)$), sum $3$ (2 pairs: $(1,2),(2,1)$), and sum $4$ (3 pairs: $(1,3),(2,2),(3,1)$). Favorable outcomes are $1 + 2 + 3 = 6$. The probability is $\\frac{6}{36} = \\frac{1}{6}$.',
  'c11-ch6-adv-q168': 'The numbers from $1$ to $30$ divisible by $5$ are $\\{5, 10, 15, 20, 25, 30\\}$, which are $6$ numbers. The probability is $\\frac{6}{30} = \\frac{1}{5}$.',
  'c11-ch6-adv-q172': 'In a standard 52-card deck, there are $4$ Queens and $4$ Kings, which are mutually exclusive events. The total number of favorable cards is $4 + 4 = 8$. Thus the probability is $\\frac{8}{52} = \\frac{2}{13}$.',
  'c11-ch6-adv-q173': 'A standard deck has $13$ hearts and $4$ aces, with $1$ card being both (the ace of hearts). By the addition law of probability: $P(\\text{Heart} \\cup \\text{Ace}) = \\frac{13 + 4 - 1}{52} = \\frac{16}{52} = \\frac{4}{13}$.',
  'c11-ch6-adv-q190': 'For each independent question with four options, the probability of guessing correctly is $\\frac{1}{4}$. By the product rule for independent events, the probability of getting all $5$ questions correct is $\\left(\\frac{1}{4}\\right)^5 = \\frac{1}{1024}$.',
  'c11-ch6-adv-q199': 'For a number formed from $\\{1, 2, 3, 4, 5\\}$ to be divisible by $5$, its last digit must be $5$ ($1$ choice). The remaining two positions can be filled by the other $4$ digits in $P(4, 2) = 4 \\times 3 = 12$ ways. Total 3-digit permutations are $P(5, 3) = 5 \\times 4 \\times 3 = 60$. Thus the probability is $\\frac{12}{60} = \\frac{1}{5}$.',
  'c11-ch6-adv-q200': 'The sum of two numbers is odd if and only if one number is even and the other is odd. In $\\{1, 2, \\dots, 10\\}$, there are $5$ odd and $5$ even numbers. The number of favorable pairs is $5 \\times 5 = 25$. The total number of pairs is $\\binom{10}{2} = \\frac{10 \\times 9}{2} = 45$. Thus the probability is $\\frac{25}{45} = \\frac{5}{9}$.',
  'c11-ch7-norm-q92': 'In $(1 + x)^n$, the coefficients of $x^3$ and $x^4$ are $\\binom{n}{3}$ and $\\binom{n}{4}$. Equating them: $\\binom{n}{3} = \\binom{n}{4} \\implies n = 3 + 4 = 7$.',
  'c11-ch7-norm-q114': 'The general term in $(x^2 + x)^6$ is $T_{r+1} = \\binom{6}{r}(x^2)^{6-r}(x)^r = \\binom{6}{r} x^{12-2r+r} = \\binom{6}{r} x^{12-r}$. Setting $12 - r = 7 \\implies r = 5$. Thus the coefficient of $x^7$ is $\\binom{6}{5} = 6$.',
  'c11-ch8-norm-q56': 'To find the $x$-intercept, set $y = 0$ in the linear equation $3x + 2(0) = 6 \\implies 3x = 6 \\implies x = \\frac{6}{3} = 2$.',
  'c11-ch8-norm-q57': 'To find the $y$-intercept, set $x = 0$ in the linear equation $3(0) + 2y = 6 \\implies 2y = 6 \\implies y = \\frac{6}{2} = 3$.',
  'c11-ch8-norm-q62': 'For $y = \\sqrt{x - 3}$ to yield real values, the radicand must be non-negative: $x - 3 \\ge 0 \\implies x \\ge 3$. At the endpoint $x = 3$, $y = \\sqrt{3 - 3} = 0$. Thus the graph begins at $(3, 0)$.',
  'c11-ch8-norm-q105': 'The vertical asymptote occurs where the denominator is zero: $x - 2 = 0 \\implies x = 2$. Since numerator and denominator have the same degree, the horizontal asymptote is the ratio of leading coefficients: $y = \\frac{1}{1} = 1$. Thus the asymptotes are $x = 2, y = 1$.',
  'c11-ch8-norm-q137': 'By definition of the inverse function, $f^{-1}(5) = 1$ is equivalent to $f(1) = 5$. Substituting into $f(x) = kx + 3$ gives $k(1) + 3 = 5 \\implies k = 5 - 3 = 2$.',
  'c11-ch8-norm-q172': 'Since $|x + 2| \\ge 0$ for all real $x$, the minimum value of $f(x) = |x + 2| - 3$ occurs when $|x + 2| = 0$ (at $x = -2$), yielding $f(-2) = -3$. As $x \\to \\pm\\infty$, $f(x) \\to \\infty$. Hence the range is $[-3, \\infty)$.',
  'c11-ch8-norm-q190': 'A fixed point of a function satisfies $f(x) = x$. Solving $\\frac{x + 2}{3} = x \\implies x + 2 = 3x \\implies 2x = 2 \\implies x = 1$.',
  'c11-ch8-norm-q198': 'Equating the line and parabola gives $x^2 = 2x + k \\implies x^2 - 2x - k = 0$. The line is tangent to the parabola when the discriminant of this quadratic equation is zero: $D = (-2)^2 - 4(1)(-k) = 4 + 4k = 0 \\implies 4k = -4 \\implies k = -1$.',
  'c11-ch9-norm-q21': 'To find the $x$-intercept, substitute $y = 0$ into $2x + y = 6 \\implies 2x + 0 = 6 \\implies 2x = 6 \\implies x = \\frac{6}{2} = 3$.',
  'c11-ch9-norm-q35': 'Setting $y = 0$ yields $3x = 12 \\implies x = 4$, giving the $x$-intercept $(4, 0)$. Setting $x = 0$ yields $2y = 12 \\implies y = 6$, giving the $y$-intercept $(0, 6)$.',
  'c11-ch9-norm-q88': 'Substitute $x = 2$ directly into the second line equation $x + y = 5$: $2 + y = 5 \\implies y = 5 - 2 = 3$. Thus the point of intersection is $(2, 3)$.',
  'c11-ch9-norm-q94': 'Subtracting the second equation $x + y = 6$ from the first equation $3x + y = 12$ eliminates $y$: $(3x + y) - (x + y) = 12 - 6 \\implies 2x = 6 \\implies x = 3$. Substituting $x = 3$ into $x + y = 6$ gives $3 + y = 6 \\implies y = 3$. Thus the point of intersection is $(3, 3)$.',
  'c11-ch10-norm-q118': 'An expression of the linear combination form $a\\sin x + b\\cos x$ has amplitude $R = \\sqrt{a^2 + b^2} = \\sqrt{8^2 + (-15)^2} = \\sqrt{64 + 225} = \\sqrt{289} = 17$. The minimum value is $-R = -17$.',
  'c11-ch10-norm-q132': 'Squaring both sides of $\\sin x + \\cos x = \\frac{\\sqrt{3}}{2}$ gives $(\\sin x + \\cos x)^2 = \\left(\\frac{\\sqrt{3}}{2}\\right)^2 \\implies \\sin^2 x + \\cos^2 x + 2\\sin x\\cos x = \\frac{3}{4}$. Since $\\sin^2 x + \\cos^2 x = 1$, we have $1 + 2\\sin x\\cos x = \\frac{3}{4} \\implies 2\\sin x\\cos x = \\frac{3}{4} - 1 = -\\frac{1}{4} \\implies \\sin x\\cos x = -\\frac{1}{8}$.',
  'c11-ch10-norm-q194': 'The expression $7\\cos x - 24\\sin x$ can be written as $R\\cos(x + \\alpha)$ where amplitude $R = \\sqrt{7^2 + (-24)^2} = \\sqrt{49 + 576} = \\sqrt{625} = 25$. The minimum value is $-R = -25$.',
  'c11-ch11-norm-q87': 'By the Law of Tangents, $\\frac{a - b}{a + b} = \\frac{\\tan\\left(\\frac{A - B}{2}\\right)}{\\tan\\left(\\frac{A + B}{2}\\right)}$. When $A = B$, $\\frac{A - B}{2} = 0$, so $\\tan(0) = 0 \\implies a - b = 0 \\implies a = b$.',
  'c11-ch11-norm-q126': 'Let $h$ be the height of the building and $x$ the original distance. Then $\\tan 30^\\circ = \\frac{h}{x} \\implies h = \\frac{x}{\\sqrt{3}}$, and after moving $50\\text{ m}$ closer, $\\tan 60^\\circ = \\frac{h}{x - 50} \\implies h = (x - 50)\\sqrt{3}$. Equating the two expressions for $h$: $\\frac{x}{\\sqrt{3}} = (x - 50)\\sqrt{3} \\implies x = 3(x - 50) \\implies x = 3x - 150 \\implies 2x = 150 \\implies x = 75\\text{ m}$.',
  'c11-ch11-norm-q183': 'The area of an equilateral triangle with side length $a$ is given by $A = \\frac{\\sqrt{3}}{4}a^2$. Setting $\\frac{\\sqrt{3}}{4}a^2 = 9\\sqrt{3} \\implies a^2 = 9 \\times 4 = 36 \\implies a = \\sqrt{36} = 6$.',
  'c11-ch12-norm-q118': 'Using the addition identity for inverse tangents $\\tan^{-1} x + \\tan^{-1} y = \\tan^{-1}\\left(\\frac{x + y}{1 - xy}\\right)$: here $\\frac{1/2 + 1/3}{1 - (1/2)(1/3)} = \\frac{5/6}{1 - 1/6} = \\frac{5/6}{5/6} = 1$. Since $xy = \\frac{1}{6} < 1$, the sum equals $\\tan^{-1}(1) = \\frac{\\pi}{4}$.',
  'c11-ch12-norm-q119': 'Using the subtraction identity $\\tan^{-1} x - \\tan^{-1} y = \\tan^{-1}\\left(\\frac{x - y}{1 + xy}\\right)$: here $\\frac{2 - 1/3}{1 + 2(1/3)} = \\frac{5/3}{5/3} = 1$. Since $xy = \\frac{2}{3} > -1$, the result is $\\tan^{-1}(1) = \\frac{\\pi}{4}$.',
  'c11-ch12-norm-q189': 'Consider $f(x) = x - \\sin x$. Its derivative is $f\'(x) = 1 - \\cos x \\ge 0$, which vanishes only at isolated points $x = 2k\\pi$, meaning $f(x)$ is strictly monotonically increasing on $\\mathbb{R}$. Since $f(0) = 0 - \\sin(0) = 0$, $x = 0$ is the unique real solution (One solution).'
};
